name: Web & API CI/CD

on:
  push:
    branches: [development]
    paths:
      - 'web/**'
      - 'api/**'
  pull_request:
    branches:
      - development
  workflow_dispatch:  # Allow manual triggers

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  WEB_IMAGE: sanjaya12345/web-app
  API_IMAGE: sanjaya12345/api-app

jobs:
  build-and-deploy-web:
    name: Build and Deploy Web
    if: contains(github.event.head_commit.modified, 'web/') || contains(github.event.head_commit.added, 'web/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Web Image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.WEB_IMAGE }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.WEB_IMAGE }}:${{ github.sha }}

      - name: Deploy Web App
        run: |
          echo "Deploying Web App with image ${{ env.DOCKER_USERNAME }}/${{ env.WEB_IMAGE }}:${{ github.sha }}"
          # Add your actual deployment commands here
          # For example, if using Kubernetes:
          # kubectl set image deployment/web-app web=${{ env.DOCKER_USERNAME }}/${{ env.WEB_IMAGE }}:${{ github.sha }}

  build-and-deploy-api:
    name: Build and Deploy API
    if: contains(github.event.head_commit.modified, 'api/') || contains(github.event.head_commit.added, 'api/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.API_IMAGE }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.API_IMAGE }}:${{ github.sha }}

      - name: Deploy API
        run: |
          echo "Deploying API with image ${{ env.DOCKER_USERNAME }}/${{ env.API_IMAGE }}:${{ github.sha }}"
          # Add your actual deployment commands here
          # For example, if using Kubernetes:
          # kubectl set image deployment/api-app api=${{ env.DOCKER_USERNAME }}/${{ env.API_IMAGE }}:${{ github.sha }}
