name: Web & API CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.changes.outputs.web }}
      api: ${{ steps.changes.outputs.api }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Detect Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - 'api/**'
            web:
              - 'web/**'

      - name: Debug Outputs
        run: |
          echo "API changed: ${{ steps.changes.outputs.api }}"
          echo "WEB changed: ${{ steps.changes.outputs.web }}"

  build-and-deploy-api:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy API
        run: echo "Deploying API..."

  build-and-deploy-web:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Web
        run: echo "Deploying Web..."
