name: Web & API CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web  # Setting correct working directory for web
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            web:
              - 'web/**'  # Detect changes in the 'web' folder

      - if: steps.changes.outputs.web == 'true'
        name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Web CI/CD
        run: echo "Web job is running in the correct directory"

  build-and-deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api  # Setting correct working directory for API
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'  # Detect changes in the 'api' folder

      - if: steps.changes.outputs.api == 'true'
        name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug API CI/CD
        run: echo "API job is running in the correct directory"
