name: Web & API CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          web:
            - 'web/**'
          api:
            - 'api/**'
          # Run backend tests only if backend files were changed
    - name: web tests
      if: steps.filter.outputs.web == 'true'
      run: echo "Executing web tests..."

    - name: api tests
      if: steps.filter.outputs.api == 'true'
      run: echo "Executing api tests..."

      
