name: Web & API CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            web:
              - 'web/**'

      - if: steps.changes.outputs.web == 'true'
        name: Debug Web CI/CD
        run: echo "Web job is running because changes were detected in 'web/'"

  build-and-deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'

      - if: steps.changes.outputs.api == 'true'
        name: Debug API CI/CD
        run: echo "API job is running because changes were detected in 'api/'"

