name: Web & API CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:  # Allow manual triggers

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.filter.outputs.web }}
      api_changed: ${{ steps.filter.outputs.api }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Detect Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - 'api/**'
            web:
              - 'web/**'

  build-and-deploy-api:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Deploying api"

  build-and-deploy-web:
    needs: detect-changes
    if: needs.detect-changes.outputs.web == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Web Docker Image
        run: echo "Deploying Web App..."  # Replace with actual deployment commands

      
