name: Web & API CI/CD

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      web-changed: ${{ steps.filter.outputs.web }}
      api-changed: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get git history for changed-files action
      
      - uses: tj-actions/changed-files@v41
        id: filter
        with:
          files: |
            web/**
            api/**
          files_separator: '\n'  # Use newline instead of comma

  build-and-deploy-web:
    needs: check-changes
    if: needs.check-changes.outputs.web-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug
        run: echo "Building web because changes were detected in web/ directory"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Web Image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/web-app:latest
            ${{ secrets.DOCKER_USERNAME }}/web-app:${{ github.sha }}

      - name: Deploy Web
        run: echo "Deploying web app..."

  build-and-deploy-api:
    needs: check-changes
    if: needs.check-changes.outputs.api-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug
        run: echo "Building api because changes were detected in api/ directory"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-app:latest
            ${{ secrets.DOCKER_USERNAME }}/api-app:${{ github.sha }}

      - name: Deploy API
        run: echo "Deploying api..."
